### ISSUE TITLE
Can't start sickbeard: No such file or directory

### ISSUE THREAD

**Issue by darkreeper** [edv/docker-sickrage#9]
Hi,

I installed the docker container with the quick setup method, but it is not possible to start the container. In protainer I get the following line in the logs:

python: can't open file '/SickRage/SickBeard.py': [Errno 2] No such file or directory,

Any idea how to solve this issue?

System: Raspbian with Raspberry 3B

**Comment by edv** [comment]
Hi, just looked into it as this repo wasn't updated for a while. Seems like it is broken for a while now. My advice would be to use the image from linuxserver.io, as it works like a charm. I will archive this repo for now.
